# docker-compose build
volumes:
  postgis-data:
    driver: local    

services:
  db:
    image: tobi312/rpi-postgresql-postgis:15-3.4-alpine-arm
    #image: postgis/postgis:15-3.3
    volumes:
      - postgis-data:/var/lib/postgresql/data
      - ./:/data
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=noisemodelling_db
      - POSTGRES_USER=noisemodelling
      - POSTGRES_PASSWORD=noisemodelling
    ports:
      - 5432:5432
    command: postgres -c max_wal_size=4GB
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 5s
      retries: 5


